### ISSUE TITLE
Please format the generated code

### ISSUE THREAD

**Issue by vHanda** [chenenyu/assets_gen#6]
Hi. Would you mind running 'flutter/dart fmt' on the generated code please. 

Many of my projects have checks to ensure that the code is formatted correct. This is usually done with a simple `dart format -o none --set-exit-if-changed .`

However, dart/flutter don't provide a way to exclude files from the formatting, and the dart team don't plan on fixing this - https://github.com/dart-lang/dart_style/issues/864 . This results in me having to implement the exclusion on my end, or format the generated code. I've finally done the latter, but I don't like having to add an explicit 'flutter format' for this package.

It would be awesome if this package could format its generated code. It would save me (and others) a lot of headache.

**Comment by chenenyu** [comment]
There is an option for formatting generated code:
```yaml
assets_gen:
  ...
  format_dart_code: true
```
Could you have a try? 😆

**Comment by vHanda** [comment]
I really should have read the docs better.

Sadly it doesn't seem to work for me. The file still isn't formatted

```
$ dart format -o none --set-exit-if-changed lib/generated/assets.dart
Changed lib/generated/assets.dart
Formatted 1 file (1 changed) in 0.12 seconds.
```

Also, out of curiosity, why not enable it by default?

**Comment by chenenyu** [comment]
Please try `1.4.1`, it should fix the format issue.

**Comment by vHanda** [comment]
Thank you. This works perfectly!
