### ISSUE TITLE
Generated Assets File has variable names with backslashes

### ISSUE THREAD

**Issue by grAPPfruit** [chenenyu/assets_gen#7]
When I run any of the build commands, the Assets file is broken because the variable names it creates contain backslashes.
Here is an example with only one asset in assets/images.

```
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'mypackage';

  static const String assets\images\bottomCurvesPng = 'assets\images\bottom-curves.png';
  static const String mypackage$assets\images\bottomCurvesPng = 'packages/mypackage/assets\images\bottom-curves.png';
}
```

I have no idea if I'm doing something wrong or what the issue is.
Would be nice if it can be addressed any time soon.

Thanks!

**Comment by chenenyu** [comment]
Hi, are you using a windows os?

**Comment by grAPPfruit** [comment]
Yes.
Ah, that would have been good information to provide.

**Comment by chenenyu** [comment]
I'll fix this issue tomorrow, thanks.

**Comment by chenenyu** [comment]
I don't have a windows computer at hand, could you please try `1.5.0` and give me a feedback if it solves this issue? 😄

**Comment by grAPPfruit** [comment]
My setup is like this:

```
assets_gen:
  class_name: Assets
  code_style: lowerCamelCase
  format_dart_code: true
  exclude:
    - assets/i18n/**
  output: assets.dart
```
I have one image "some-image.png" in the subfolder images.

I'd expect, that after generating I can access it with `Assets.images.someImage`
But actually I have two constants, and they look like this:
```
Assets.assetsImagesSomeImagePng;
Assets.bildersprache$assetsImagesSomeImagePng;
```

So yes, it works in a way that it doesn't produce an error anymore, but it doesn't work as expected (described).

**Comment by chenenyu** [comment]
Yeah, `assets_gen` generates a "single-line"(not nested) file as so far, and it will provide a nested production in the future.
