### ISSUE TITLE
Cannot use const assets name anymore

### ISSUE THREAD

**Issue by Nico04** [chenenyu/assets_gen#8]
I have several const that defines some static data in my app.
Before using `assets_gen`, I could write something like this :
`const breath = MultiSelectorItem('breath', 'assets/breath.svg', 'Breath');`

But when using `assets_gen`, this line doesn't work anymore :
`const breath = MultiSelectorItem('breath', Assets.breath.path, 'Breath');`

It seems that it's because the generated class `SvgGenImage.path` is a getter, so NOT const.

```
class SvgGenImage {
  const SvgGenImage(this._assetName);

  final String _assetName;

  [...]

  String get path => _assetName;
  String get keyName => _assetName;
}
```

Do you have an idea how can I use the asset path in a const ?

EDIT : 
I now I could remove `flutter_svg: true` in `pubspec`, but using this kind of code is also handy :
`child: Assets.breath.svg()`

**Comment by chenenyu** [comment]
https://github.com/FlutterGen/flutter_gen
